# Generated by Django 3.2.4 on 2021-06-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
